[package]
name = "onepass-conf"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
onepass-seed = "3.0.0-pre.0"
serde = { version = "1.0.228", default-features = false, features = ["derive", "std"] }
toml = "0.9.11"

[dev-dependencies]
tempfile = "3.24.0"
